use rand::Rng;

pub const FIRST_NAMES: &[&str] = &[
    // Common English first names
    "James", "Mary", "Robert", "Patricia", "John", "Jennifer", "Michael", "Linda",
    "David", "Elizabeth", "William", "Barbara", "Richard", "Susan", "Joseph", "Jessica",
    "Thomas", "Sarah", "Charles", "Karen", "Christopher", "Lisa", "Daniel", "Nancy",
    "Matthew", "Betty", "Anthony", "Margaret", "Mark", "Sandra", "Donald", "Ashley",
    "Steven", "Kimberly", "Paul", "Emily", "Andrew", "Donna", "Joshua", "Michelle",
    "Kenneth", "Dorothy", "Kevin", "Carol", "Brian", "Amanda", "George", "Melissa",
    "Timothy", "Deborah", "Ronald", "Stephanie", "Edward", "Rebecca", "Jason", "Sharon",
    "Jeffrey", "Laura", "Ryan", "Cynthia", "Jacob", "Kathleen", "Gary", "Amy",
    "Nicholas", "Angela", "Eric", "Shirley", "Jonathan", "Anna", "Stephen", "Brenda",
    "Larry", "Pamela", "Justin", "Emma", "Scott", "Nicole", "Brandon", "Helen",
    "Benjamin", "Samantha", "Samuel", "Katherine", "Raymond", "Christine", "Gregory", "Debra",
    "Frank", "Rachel", "Alexander", "Carolyn", "Patrick", "Janet", "Jack", "Catherine",
    "Dennis", "Maria", "Jerry", "Heather", "Tyler", "Diane", "Aaron", "Ruth",
    "Jose", "Julie", "Adam", "Olivia", "Nathan", "Joyce", "Henry", "Virginia",
    "Peter", "Victoria", "Zachary", "Kelly", "Douglas", "Lauren", "Harold", "Christina",
    // Additional diverse names
    "Alejandro", "Aisha", "Wei", "Fatima", "Hiroshi", "Priya", "Omar", "Mei",
    "Sanjay", "Yuki", "Mohamed", "Ling", "Carlos", "Ananya", "Kenji", "Zara",
    "Luis", "Nadia", "Raj", "Sakura", "Ahmed", "Xiaoli", "Diego", "Sunita",
    "Ibrahim", "Hana", "Andrei", "Svetlana", "Dmitri", "Olga", "Nikolai", "Tatiana",
    "Pedro", "Sofia", "Ricardo", "Isabella", "Marco", "Giulia", "Luca", "Chiara",
    "Hans", "Ingrid", "Lars", "Freya", "Erik", "Astrid", "Sven", "Brigitte",
    "Jean", "Marie", "Pierre", "Camille", "Antoine", "Chloe", "Ethan", "Mia",
    "Noah", "Ava", "Liam", "Sophia", "Mason", "Amelia", "Logan", "Harper",
    "Lucas", "Ella", "Aiden", "Abigail", "Jackson", "Charlotte", "Sebastian", "Luna",
    "Mateo", "Penelope", "Owen", "Layla", "Elijah", "Riley", "Oliver", "Zoey",
    "Caleb", "Nora", "Leo", "Lily", "Isaac", "Eleanor", "Gabriel", "Hannah",
    "Julian", "Lillian", "Grayson", "Addison", "Jaxon", "Aubrey", "Levi", "Ellie",
    "Isaiah", "Stella", "Lincoln", "Natalie", "Connor", "Zoe", "Maverick", "Leah",
    "Josiah", "Hazel", "Ezra", "Violet", "Kai", "Aurora", "Miles", "Savannah",
    "Asher", "Audrey", "Nolan", "Brooklyn", "Cooper", "Bella", "Ian", "Claire",
    "Kwame", "Amara", "Tariq", "Leila", "Jamal", "Imani", "Kofi", "Nia",
    "Ravi", "Deepa", "Arjun", "Kavya", "Vikram", "Pooja", "Amit", "Neha",
    "Takeshi", "Akiko", "Haruto", "Rin", "Ryu", "Ayumi", "Daiki", "Nanami",
    "Jian", "Xia", "Feng", "Yan", "Bo", "Lian", "Chen", "Min",
    "Eoin", "Siobhan", "Cian", "Aoife", "Declan", "Niamh", "Finn", "Saoirse",
    "Matias", "Valentina", "Santiago", "Camila", "Thiago", "Martina", "Emilio", "Lucia",
    "Adrian", "Gabriela", "Hugo", "Elena", "Felix", "Adriana", "Max", "Natalia",
    "Oscar", "Rosa", "Ivan", "Ana", "Roman", "Vera", "Axel", "Daria",
    "Tristan", "Celeste", "Silas", "Ivy", "Jasper", "Ruby", "Rowan", "Willow",
    "Atlas", "Sage", "Beckett", "Jade", "Colton", "Aria", "Xavier", "Nova",
    "Milo", "Iris", "Theodore", "Cora", "August", "Lydia", "Arthur", "Eliza",
];

pub const LAST_NAMES: &[&str] = &[
    // Common English surnames
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
    "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson",
    "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson",
    "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker",
    "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill",
    "Flores", "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell",
    "Mitchell", "Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz",
    "Parker", "Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris", "Morales",
    "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper", "Peterson",
    "Bailey", "Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward",
    "Richardson", "Watson", "Brooks", "Chavez", "Wood", "James", "Bennett", "Gray",
    "Mendoza", "Ruiz", "Hughes", "Price", "Alvarez", "Castillo", "Sanders", "Patel",
    "Myers", "Long", "Ross", "Foster", "Jimenez", "Powell", "Jenkins", "Perry",
    "Russell", "Sullivan", "Bell", "Coleman", "Butler", "Henderson", "Barnes", "Gonzales",
    // Additional diverse surnames
    "O'Brien", "O'Connor", "Murphy", "Walsh", "Byrne", "Ryan", "O'Sullivan", "O'Neill",
    "Kennedy", "McLaughlin", "Fitzgerald", "Brennan", "Doyle", "Kavanagh", "Gallagher",
    "Chen", "Wang", "Zhang", "Li", "Liu", "Yang", "Huang", "Wu",
    "Zhou", "Xu", "Sun", "Ma", "Zhu", "Lin", "Guo", "He",
    "Tanaka", "Suzuki", "Watanabe", "Takahashi", "Ito", "Yamamoto", "Nakamura", "Kobayashi",
    "Sato", "Kato", "Yoshida", "Yamada", "Sasaki", "Yamaguchi", "Matsumoto", "Inoue",
    "Kumar", "Singh", "Sharma", "Gupta", "Verma", "Joshi", "Mishra", "Reddy",
    "Rao", "Nair", "Mehta", "Shah", "Agarwal", "Chopra", "Malik", "Kapoor",
    "Khan", "Ali", "Hassan", "Ahmed", "Hussein", "Ibrahim", "Abbas", "Farouk",
    "Mueller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker",
    "Schulz", "Hoffmann", "Schaefer", "Koch", "Bauer", "Richter", "Klein", "Wolf",
    "Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano", "Colombo", "Ricci",
    "Marino", "Greco", "Bruno", "Gallo", "Conti", "DeLuca", "Mancini", "Costa",
    "Dupont", "Martin", "Bernard", "Dubois", "Thomas", "Robert", "Richard", "Petit",
    "Durand", "Leroy", "Moreau", "Simon", "Laurent", "Lefebvre", "Michel", "Garcia",
    "Ivanov", "Smirnov", "Kuznetsov", "Popov", "Volkov", "Sokolov", "Lebedev", "Kozlov",
    "Novikov", "Morozov", "Petrov", "Fedorov", "Mikhailov", "Nikolaev", "Pavlov",
    "da Silva", "Santos", "Oliveira", "Souza", "Pereira", "Ferreira", "Almeida", "Costa",
    "Rodrigues", "Carvalho", "Gomes", "Martins", "Araujo", "Melo", "Barbosa", "Ribeiro",
    "Park", "Choi", "Jeong", "Kang", "Yoon", "Jang", "Lim", "Han",
    "Shin", "Kwon", "Son", "Hwang", "Ahn", "Yoo", "Hong", "Jeon",
    "Okafor", "Adeyemi", "Okonkwo", "Abubakar", "Nwosu", "Eze", "Olawale", "Balogun",
    "Mensah", "Owusu", "Asante", "Boateng", "Adjei", "Agyeman", "Appiah", "Darko",
    "Johansson", "Andersson", "Karlsson", "Nilsson", "Eriksson", "Larsson", "Olsson", "Persson",
    "Svensson", "Gustafsson", "Lindberg", "Lindqvist", "Lindgren", "Berg", "Lund", "Holm",
];

pub fn random_name(rng: &mut impl Rng) -> String {
    let first = FIRST_NAMES[rng.gen_range(0..FIRST_NAMES.len())];
    let last = LAST_NAMES[rng.gen_range(0..LAST_NAMES.len())];
    format!("{} {}", first, last)
}
